### ISSUE TITLE
"LNK1107 invalid or corrupt file" error when running example

### ISSUE THREAD

**Issue by corybarr** [kritzikratzi/ofxAvCodec#10]
Hello. I've been wrestling with FFmpeg for a while now. There seems to be little documentation, tutorials, or examples. So this addon looks very helpful.

Trying to run the example, I get the following linker error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1107	invalid or corrupt file: cannot read at 0x3D8	ofxAvCodecExample	D:\oF\of_v0.9.8_vs_release\addons\ofxAvCodec\libs\avcodec\lib\vs\Win32\avcodec-57.dll	1	

I'm using the downloaded binaries from this repo. I'm not sure how to fix the error. Do the binaries need to be rebuilt?

Thanks.

**Comment by kritzikratzi** [comment]
is it possible you're linking to the dll files instead of the lib files?

**Comment by corybarr** [comment]
Ah, yes. You're correct. The downloaded binaries have both the DLL and lib files in them, so the oF Project Generator added the DLLs to Linker->Input->Additional Dependencies. It works now.

Thanks for putting in the effort on this.

**Comment by kritzikratzi** [comment]
glad you got it to work :)
