### ISSUE TITLE
won't compile of0.9.8 OSX 10.11.6

### ISSUE THREAD

**Issue by steeley** [kritzikratzi/ofxAvCodec#13]
followed the setup instructions and get these error on compile:

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libavfilter.5.21.100.dylib'

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libavutil.54.28.100.dylib'

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libswscale.3.1.101.dylib'

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libavdevice.56.4.100.dylib'

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libavformat.56.40.100.dylib'

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libswresample.1.2.100.dylib'

clang: error: no such file or directory: '../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libavcodec.56.47.100.dylib'

**Comment by kritzikratzi** [comment]
that's just the example, it's missing ffmpeg (as explained in the instructions).
