### ISSUE TITLE
How to use ofxAvCodec for Android?

### ISSUE THREAD

**Issue by Katmai6** [kritzikratzi/ofxAvCodec#16]
I downloaded ofxAvCodec into Openframeworks' "addons" directory.I am using project generator to create a project including the ofxAvCodec addon.I wanted to use precompiled libraries for ofxAvCodec/ffmpeg from your website but I think it doesn't include libraries for Android/armeabi-v7a.

I downloaded a precompiled ffmpeg library from web and copied into "openframeworks\addons\ofxAvCodec\libs\avcodec\lib" but Android Studio seems like it doesn't see these library files, it still gives "undefined reference to this function" like errors when I try to compile the project.

Could you help please?I should say I am very inexperienced about adding libraries.

**Comment by kritzikratzi** [comment]
the only thing i can say for sure: add the libraries _before_ (!) using the project generator. and the lib folder needs to include your architecture. it should probably be something along the lines of `openframeworks\addons\ofxAvCodec\libs\avcodec\lib\armv7s` (either check in the PG source where it's looking, or compare with other addons with native libs). 

if you want to update the readme or provide android binaries please send a PR!
