### ISSUE TITLE
improve a/v sync in video player

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/ofxAvCodec#3]
currently videos with too long audio sections or (a/v too far apart in the container) don't play steadily.

**Comment by kritzikratzi** [comment]
latest commit on the video branch should improve the current situation.

**Comment by fakob** [comment]
I tested it with different videos and for some of them it seemed to be solved. For the others, they now play in different speeds with the audio and video being out of sync pretty soon. Also some start hanging again. I have attached a sample clip.
[FailSample.mov.zip](https://github.com/kritzikratzi/ofxAvCodec/files/234915/FailSample.mov.zip)

**Comment by kritzikratzi** [comment]
running the video through ffprobe i can see that there the audio and video don't start at the same time, that's why they are out of sync. 

```
Duration: 00:01:02.26, start: 0.020922, bitrate: 660 kb/s
    Chapter #0:0: start -483.082600, end 545.545000
```

but the offset stays constant throughout the entire video. 
do you also have a clip where they go more and more out of sync while playing?

**Comment by fakob** [comment]
Currently on vacation so I haven't had time to spend on that. As I have always only cared about frame accuracy in an image level, I am not sure if I have a clip for you. I can check when getting back next week.

**Comment by fakob** [comment]
As I could not reproduce the ffprobe output, I could not look for another clip which gets more and more out of sync. The FailSample.mov was sent to me as an example not working with my MoviePrint tool, so I do not know how to reproduce that either. I know that videos encoded with [Handbrake](https://handbrake.fr/) always made problems. Not sure if that helps.
