### ISSUE TITLE
Where to find  Configuration > Linker > Extended 

### ISSUE THREAD

**Issue by clankill3r** [kritzikratzi/ofxAvCodec#5]
hi, following your instructions i'm stuck at:

> Configuration > Linker > Extended > SAFESH:NO
> set to no (if you cant find the option add /SAFESEH:NO as a custom linker flag)

Is that changed in VS. If I go to the properties then I can find the linker, but not the extended.

**Comment by kritzikratzi** [comment]
no, it has not moved: https://msdn.microsoft.com/en-us/library/9a89h429.aspx

**Comment by clankill3r** [comment]
I don't need it anymore but be aware that your instructions are still outdated in:

https://github.com/kritzikratzi/ofxAvCodec/blob/master/readme.md

**Comment by kritzikratzi** [comment]
quite possible. feel free to make a PR ^^
