### ISSUE TITLE
OS X OF 0.9.3

### ISSUE THREAD

**Issue by stephanschulz** [kritzikratzi/ofxAvCodec#6]
hi 
i am trying to get your addon running on my OS X machine with OF 0.9.3 but get lot's of 

downloaded the lib zip here https://github.com/kritzikratzi/ofxAvCodec/releases
changed "development target" to 10.11. it was set to 10.6
changed "library search path to " ../../../addons/ofxAvCodec/libs/avcodec/lib/osx , because it was linked to your user name

now get these errors
<img width="1401" alt="screen shot 2017-01-20 at 9 27 40 am" src="https://cloud.githubusercontent.com/assets/1054816/22152886/d99d900c-def2-11e6-8486-4b00b485c58f.png">
:

**Comment by kritzikratzi** [comment]
hi! 

sorry, the example project is really old. 
i set it up like this: 

1. create a new project (no addons) with the project generator 
2. run `ofxcode add ofxAvCodec` (this sets up include paths, adds the sources, and modifies the run scripts phase so the dylibs are copy into the destination app bundle) 

you can grab ofxcode from here: https://github.com/kritzikratzi/ofxcode (see the releases tab for binaries!)
or, if you want to do it manually: 

1. create a new addons/ofxAvCodec/src group in your project + add the files
2. add addons/ofxAvCodec/libs/avcodec/include to your user header search paths
3. add addons/ofxAvCodec/libs/avcodec/lib/ to your library search path
4. add this to your scripts phase: `rsync -aved ../../../addons/ofxAvCodec/libs/avcodec/lib/osx/*.dylib "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS" 2>/dev/null | echo -n`

(didn't test the manual process, i always use the ofxcode)
