### ISSUE TITLE
time.h conflict

### ISSUE THREAD

**Issue by DHaylock** [kritzikratzi/ofxAvCodec#7]
Hi @kritzikratzi,

Just wondering have you had any issues with avutil time.h conflicting with standard time.h?

I get 21 error all linking to ctime.

<code>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:56:9: No member named 'clock_t' in the global namespace
</code>

I've tried numerous fixes and recompiled FFmpeg a few times to no avail. 
Any thoughts welcome.

Cheers

**Comment by kritzikratzi** [comment]
add the directory to your user include paths, and set the "always prefer user includes" to no.
no need to add the actual files in ofxAvCodec/libs/avcodec/include directly to your project.

**Comment by kritzikratzi** [comment]
ps.  i just realize i never published the new binaries. 
please follow this: https://github.com/kritzikratzi/ofxAvCodec/issues/8
i'll try to do it asap.

**Comment by DHaylock** [comment]
Cheers @kritzikratzi

**Comment by kritzikratzi** [comment]
Ok, OSX release is here: https://github.com/kritzikratzi/ofxAvCodec/releases/tag/0.2
windows libs will follow soon (i'm not near that computer at the moment). 

could you fix your issues with time.h?

**Comment by DHaylock** [comment]
Hi @kritzikratzi 

Awesome, cheers.

I emulated the example removed files and relinked the libs.
time.h error seems to have disappeared 👍 

Now am getting this lovely message.

<code>dyld: Library not loaded: @executable_path/libavdevice.56.dylib
  Referenced from: /bin/FFmpegDebug.app/Contents/MacOS/FFmpegDebug
  Reason: no suitable image found.  Did find:
</code>

**Comment by DHaylock** [comment]
Hi @kritzikratzi 

Added the new binaries seems happy with that.

Can not find "Always prefer user includes" anywhere but "Always Search User Path" set to no removes the time.h error

Now have 

<code>dyld: Library not loaded: @executable_path/libopenh264.dylib
  Referenced from: /Users/david/Desktop/of_v0.9.8_osx_release/apps/myApps/FFmpeg/bin/FFmpegDebug.app/Contents/MacOS/FFmpegDebug
  Reason: image not found</code>

Sorry about this :)

**Comment by DHaylock** [comment]
Got it, this should solve it.

<code>cp -fR ../../../addons/ofxAvCodec/libs/avcodec/lib/osx/libopenh264.dylib "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS" 2>/dev/null | echo -n</code>

**Comment by kritzikratzi** [comment]
great. yes, you need to do this. closing it then. 

for the next project you might want to use my [ofxcode](https://github.com/kritzikratzi/ofxcode) utility like so on the command line: 

	ofxcode add ofxAvCodec
	ofxcode remove ofxAvCodec

it performs all the necessary steps (except the "always prefer user includes" setting).
